version: '3.8'

services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    image: api-gateway
    container_name: api-gateway
    ports:
      - "9000:9000"
    restart: always
    networks:
      - demo-network

networks:
  demo-network:
    external: true

