services:
  config-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: eureka-service
    container_name: eureka-service
    ports:
      - "8761:8761"
    networks:
      - demo-network


networks:
  demo-network:
    external: true
