version: '3.8'

services:
  employee-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: employee-service
    container_name: employee-service
    ports:
      - "8090:8090"
    restart: always
    networks:
      - api-gateway
    depends_on:
      - specialization-service
      - user-service
      - employee_db

  employee_db:
    image: postgres:17.0
    command:
      - "postgres"
      - "-c"
      - "port=5442"
    container_name: employee_db
    environment:
      POSTGRES_DB: employee_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "password"
    volumes:
      - employee_db:/var/lib/postgresql/data
    ports:
      - "5442:5442"
    networks:
      - api-gateway
  
  user-service:
    build:
      context: ../user-service
      dockerfile: Dockerfile
    image: user-service
    container_name: user-service
    ports:
      - "8080:8080"
    restart: always
    networks:
      - api-gateway
    depends_on:
      - user_db
  
  user_db:
    image: postgres:17.0
    container_name: user_db
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "password"
    volumes:
      - user_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - api-gateway

  specialization-service:
    build:
      context: ../specialization-service
      dockerfile: Dockerfile
    image: specialization-service
    container_name: specialization-service
    ports:
      - "8070:8070"
    networks:
      - api-gateway
    restart: always
    depends_on:
      - specialization_db

  specialization_db:
    image: postgres:17.0
    command:
      - "postgres"
      - "-c"
      - "port=5445"
    container_name: specialization_db
    environment:
      POSTGRES_DB: specialization_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "password"
    volumes:
      - specialization_db:/var/lib/postgresql/data
    ports:
      - "5445:5445"
    networks:
      - api-gateway

volumes:
  user_db:
  employee_db:
  specialization_db:

networks:
  api-gateway:
    driver: bridge
