services:
  employee-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: employee-service
    container_name: employee-service
    ports:
      - "8090:8090"
    restart: always
    networks:
      - demo-network
    depends_on:
      - employee_db

  employee_db:
    image: postgres:17.0
    command:
      - "postgres"
      - "-c"
      - "port=5442"
    container_name: employee_db
    environment:
      POSTGRES_DB: employee_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "password"
    volumes:
      - employee_db:/var/lib/postgresql/data
    ports:
      - "5442:5442"
    networks:
      - demo-network

volumes:
  employee_db:

networks:
  demo-network:
    external: true
