version: '3.8'

services:
  demo_two:
    build:
      context: .
      dockerfile: Dockerfile
    image: demo_two
    container_name: demo_two
    ports:
      - "8090:8090"
    restart: always
    depends_on:
      - postgres

  postgres:
    image: postgres:17.0
    command:
      - "postgres"
      - "-c"
      - "port=5442"
    container_name: employee_db
    environment:
      POSTGRES_DB: employee_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "password"
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5442:5442"

volumes:
  pgdata:
