version: '3.8'

services:
  demo_one:
    build:
      context: .
      dockerfile: Dockerfile
    image: demo_one
    container_name: demo_one
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - postgres

  postgres:
    image: postgres:17.0
    container_name: postgres
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "password"
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
