services:
  user-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: user-service
    container_name: user-service
    ports:
      - "8080:8080"
    networks:
      - demo-network
    restart: always
    depends_on:
      - user_db

  user_db:
    image: postgres:17.0
    container_name: user_db
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "password"
    volumes:
      - user_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - demo-network

volumes:
  user_db:

networks:
  demo-network:
    external: true
